name: HTML CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_html:
    name: Lint HTML
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install html‑hint
        run: npm install -g htmlhint

      - name: Lint HTML files
        run: htmlhint "./*.html"
